ALTER AUTHENTICATION localpwd METHOD 'trust';

ALTER AUTHENTICATION ident1 SET system_users='user1';

ALTER ACCESS POLICY ON customer FOR ROWS WHERE cid1>1 ENABLE;

ALTER ACCESS POLICY ON customer FOR COLUMN test COPY TO TABLE test;

ALTER FAULT GROUP parent0 RENAME TO parent100;

ALTER FUNCTION SQL_one (a,b) RENAME TO SQL_two;

ALTER FUNCTION SQL_two (int, int) SET SCHEMA macros;

ALTER FUNCTION SQL_one (int, int) RENAME TO SQL_two;

ALTER FUNCTION UDF_two (int, int) SET FENCED false;

ALTER HCATALOG SCHEMA hcat SET HOSTNAME='test';

ALTER LIBRARY myFunctions AS '/home/dbadmin/my_new_functions.so';

ALTER MODEL db.tschema.test OWNER TO testOwner;

ALTER NETWORK INTERFACE myNetwork RENAME TO myNewNetwork;

ALTER NODE v_vmart_node0001 EXPORT ON DEFAULT;

ALTER PROJECTION tbl_p RENAME to new_tbl_p;

ALTER PROFILE DEFAULT LIMIT PASSWORD_MIN_SYMBOLS 'asdsd';

ALTER PROFILE sample_profile RENAME TO new_sample_profile;


 ALTER SCHEMA ms OWNER TO dbadmin CASCADE;
 
 
 
 ALTER SCHEMA S1, S2, temps RENAME TO temps, S1, S2;
 
 ALTER SCHEMA s1 DEFAULT INCLUDE SCHEMA PRIVILEGES;
 
 ALTER SEQUENCE my_sequence RESTART WITH 50;
 
 ALTER SESSION CLEAR ForceUDxFencedMode;
 
 ALTER SESSION SET ForceUDxFencedMode = 1;
 
 ALTER SESSION SET UDPARAMETER FOR MyLibrary RowCount = 25;
 
 ALTER SESSION CLEAR UDPARAMETER FOR MyLibrary RowCount;
 
 ALTER SESSION CLEAR UDPARAMETER FOR MyLibrary;
 
 ALTER SUBNET mysubnet RENAME TO myNewSubnet;
 
 ALTER TABLE mytable RENAME TO mytable2;
 
 
 BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED READ WRITE;
 
 COMMENT ON COLUMN customer_dimension_vmart_node01.customer_name IS NULL;
 
 SHOW CURRENT ALL;
 
 SHOW ALL;
 
 SHOW DATABASE DEFAULT ALL;
 
 SHOW NODE v_vmart_node0001 ALL;
 
 SHOW SESSION UDPARAMETERS ALL;
 
 START TRANSACTION ISOLATION LEVEL READ COMMITTED READ WRITE;
 
 SET SESSION TEMPSPACECAP NONE;
 
 SET SESSION RESOURCE_POOL = ceo_pool;
 
 SET SESSION MULTIPLEACTIVERESULTSETS TO on;
 
 SET SESSION MEMORYCAP '2G';
 
 SET ROLE all; 